[package]
name = "cli"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
sprite_dicing = { path = "../lib" }
image = { version = "0.25", default-features = false, features = [
    "rayon",
    "png",
    "webp",
    "tga",
    "dds",
    "tiff",
    "jpeg",
    "bmp"
] }
rayon = "1.12"
clap = { version = "4.6", features = ["derive"] }
indicatif = "0.18"
